/* ============================================================================
   MovieFilterr — curated parental-guidance dataset
   ----------------------------------------------------------------------------
   Each title carries a list of `advisories`, where every advisory is a single
   parental-guidance notice pinned to a timestamp (in seconds from the start).

   category : one of CATEGORIES keys below
   severity : 1 = mild | 2 = moderate | 3 = strong
   t        : timestamp in seconds (when the notice occurs)
   note     : short human description of the moment

   NOTE ON DATA: timecodes here are hand-authored, illustrative reference data
   for well-known titles — not an authoritative frame-accurate log. No public
   API exposes timestamped advisories, so this dataset is the demonstration
   layer. Swap `DATA` for a live source and the whole UI keeps working.
   ========================================================================== */

const CATEGORIES = {
  nudity:      { label: "Nudity & Sex",        color: "#ff5d8f", glyph: "◐" },
  violence:    { label: "Violence & Gore",     color: "#ff5247", glyph: "✶" },
  profanity:   { label: "Profanity",           color: "#ffb443", glyph: "§" },
  substances:  { label: "Alcohol & Drugs",     color: "#5dd39e", glyph: "❖" },
  frightening: { label: "Frightening & Intense", color: "#9d7bff", glyph: "❍" },
  other:       { label: "Mature Themes",       color: "#6ec1ff", glyph: "◇" },
};

const SEVERITY = {
  1: { label: "Mild",     dots: 1 },
  2: { label: "Moderate", dots: 2 },
  3: { label: "Strong",   dots: 3 },
};

// helper: minutes -> seconds for readability while authoring
const m = (min, sec = 0) => min * 60 + sec;

const DATA = [
  {
    id: "titanic-1997",
    title: "Titanic",
    year: 1997,
    type: "movie",
    cert: "PG-13",
    runtime: m(194),
    genres: ["Romance", "Drama"],
    tagline: "Nothing on Earth could come between them.",
    advisories: [
      { category: "substances",  severity: 1, t: m(40),     note: "Social drinking and smoking in the first-class dining saloon." },
      { category: "profanity",   severity: 1, t: m(52),     note: "Scattered mild profanity ('hell', 'damn')." },
      { category: "nudity",      severity: 2, t: m(66),     note: "Jack sketches Rose nude — full female nudity in an artistic context." },
      { category: "nudity",      severity: 2, t: m(73, 30), note: "A brief intimate scene in the cargo hold; fogged handprint, partial." },
      { category: "frightening", severity: 3, t: m(150),    note: "The ship strikes the iceberg; rising panic below decks." },
      { category: "violence",    severity: 2, t: m(160),    note: "Crowd crush at the gates; an officer fires into the panic." },
      { category: "frightening", severity: 3, t: m(168),    note: "The stern rises and the ship splits — mass drowning in freezing water." },
    ],
  },
  {
    id: "dark-knight-2008",
    title: "The Dark Knight",
    year: 2008,
    type: "movie",
    cert: "PG-13",
    runtime: m(152),
    genres: ["Action", "Crime", "Thriller"],
    tagline: "Why so serious?",
    advisories: [
      { category: "violence",    severity: 3, t: m(18),  note: "Opening bank heist — point-blank shootings as the crew turns on itself." },
      { category: "profanity",   severity: 1, t: m(10),  note: "Mild language throughout ('hell', 'damn')." },
      { category: "frightening", severity: 3, t: m(60),  note: "The Joker's 'pencil trick'; sustained menace and threats." },
      { category: "violence",    severity: 2, t: m(78),  note: "A man's face is threatened with a knife; intimidation." },
      { category: "frightening", severity: 2, t: m(120), note: "Harvey Dent's burned face revealed; disfigurement." },
      { category: "other",       severity: 2, t: m(132), note: "Two ferries rigged to explode — moral-terror hostage scenario." },
    ],
  },
  {
    id: "matrix-1999",
    title: "The Matrix",
    year: 1999,
    type: "movie",
    cert: "R",
    runtime: m(136),
    genres: ["Sci-Fi", "Action"],
    tagline: "Free your mind.",
    advisories: [
      { category: "frightening", severity: 2, t: m(28),  note: "A robotic 'bug' burrows into Neo's navel; body horror." },
      { category: "frightening", severity: 2, t: m(40),  note: "Neo wakes in a pod farm of harvested humans; unsettling imagery." },
      { category: "profanity",   severity: 2, t: m(55),  note: "Occasional strong language." },
      { category: "violence",    severity: 3, t: m(106), note: "Lobby shootout — heavy stylized gunplay and casualties." },
      { category: "violence",    severity: 2, t: m(118), note: "Rooftop and subway fights; a point-blank standoff." },
    ],
  },
  {
    id: "inception-2010",
    title: "Inception",
    year: 2010,
    type: "movie",
    cert: "PG-13",
    runtime: m(148),
    genres: ["Sci-Fi", "Thriller", "Action"],
    tagline: "Your mind is the scene of the crime.",
    advisories: [
      { category: "profanity",   severity: 1, t: m(22),  note: "A few mild words." },
      { category: "violence",    severity: 2, t: m(64),  note: "Gunfights across nested dream levels; projections attack." },
      { category: "frightening", severity: 2, t: m(96),  note: "A van plunges off a bridge in slow motion; drowning peril." },
      { category: "frightening", severity: 2, t: m(120), note: "A decaying dream-world ('Limbo') crumbles into the sea." },
    ],
  },
  {
    id: "pulp-fiction-1994",
    title: "Pulp Fiction",
    year: 1994,
    type: "movie",
    cert: "R",
    runtime: m(154),
    genres: ["Crime", "Drama"],
    tagline: "Just because you are a character doesn't mean you have character.",
    advisories: [
      { category: "profanity",   severity: 3, t: m(4),   note: "Pervasive strong profanity from the opening scene onward." },
      { category: "violence",    severity: 3, t: m(26),  note: "An accidental point-blank shooting; graphic aftermath." },
      { category: "substances",  severity: 3, t: m(48),  note: "Heroin use and an overdose; an adrenaline needle to the chest." },
      { category: "nudity",      severity: 2, t: m(108), note: "A sexual-assault scene in a back room; partial nudity, disturbing." },
    ],
  },
  {
    id: "interstellar-2014",
    title: "Interstellar",
    year: 2014,
    type: "movie",
    cert: "PG-13",
    runtime: m(169),
    genres: ["Sci-Fi", "Drama", "Adventure"],
    tagline: "Mankind was born on Earth. It was never meant to die here.",
    advisories: [
      { category: "profanity",   severity: 1, t: m(35),  note: "Mild language at moments of stress." },
      { category: "frightening", severity: 3, t: m(70),  note: "A kilometre-high tidal wave on the water planet; drowning peril." },
      { category: "violence",    severity: 2, t: m(118), note: "A fistfight on the ice planet; a spacesuit is breached." },
      { category: "frightening", severity: 2, t: m(124), note: "A docking spin sequence — disorientating, high tension." },
    ],
  },
  {
    id: "wolf-of-wall-street-2013",
    title: "The Wolf of Wall Street",
    year: 2013,
    type: "movie",
    cert: "R",
    runtime: m(180),
    genres: ["Comedy", "Crime", "Drama"],
    tagline: "More is never enough.",
    advisories: [
      { category: "profanity",   severity: 3, t: m(3),   note: "Record-setting, wall-to-wall strong profanity." },
      { category: "nudity",      severity: 3, t: m(12),  note: "Explicit nudity and sexual content; recurs throughout the film." },
      { category: "substances",  severity: 3, t: m(20),  note: "Constant drug use — cocaine and quaaludes — played for excess." },
      { category: "other",       severity: 2, t: m(90),  note: "Relentless debauchery, fraud and reckless behaviour." },
      { category: "nudity",      severity: 3, t: m(132), note: "Extended explicit sexual content." },
    ],
  },
  {
    id: "mad-max-fury-road-2015",
    title: "Mad Max: Fury Road",
    year: 2015,
    type: "movie",
    cert: "R",
    runtime: m(120),
    genres: ["Action", "Adventure", "Sci-Fi"],
    tagline: "What a lovely day.",
    advisories: [
      { category: "frightening", severity: 2, t: m(10),  note: "Grotesque War Boys and the tyrant Immortan Joe; oppressive imagery." },
      { category: "violence",    severity: 3, t: m(34),  note: "Vehicular carnage — impalements, explosions, hand-to-hand brutality." },
      { category: "other",       severity: 2, t: m(48),  note: "Themes of captivity and forced servitude (handled without nudity)." },
      { category: "frightening", severity: 2, t: m(60),  note: "A towering sandstorm swallows the convoy." },
    ],
  },
  {
    id: "parasite-2019",
    title: "Parasite",
    year: 2019,
    type: "movie",
    cert: "R",
    runtime: m(132),
    genres: ["Thriller", "Drama", "Comedy"],
    tagline: "Act like you own the place.",
    advisories: [
      { category: "profanity",   severity: 2, t: m(18),  note: "Strong language throughout." },
      { category: "nudity",      severity: 2, t: m(56),  note: "A sexual scene on the living-room couch; partial nudity." },
      { category: "frightening", severity: 2, t: m(84),  note: "A hidden basement is discovered; a sudden flood displaces a family." },
      { category: "violence",    severity: 3, t: m(118), note: "A birthday-party massacre — sudden, bloody stabbings." },
    ],
  },
  {
    id: "spider-verse-2018",
    title: "Spider-Man: Into the Spider-Verse",
    year: 2018,
    type: "movie",
    cert: "PG",
    runtime: m(117),
    genres: ["Animation", "Action", "Adventure"],
    tagline: "More than one wears the mask.",
    advisories: [
      { category: "profanity",   severity: 1, t: m(14),  note: "Very mild language." },
      { category: "violence",    severity: 1, t: m(40),  note: "Stylized comic-book action and brawls." },
      { category: "frightening", severity: 2, t: m(28),  note: "A hero is killed by the Kingpin; the unstable collider menaces the city." },
    ],
  },
  {
    id: "get-out-2017",
    title: "Get Out",
    year: 2017,
    type: "movie",
    cert: "R",
    runtime: m(104),
    genres: ["Horror", "Thriller", "Mystery"],
    tagline: "Just because you're invited, doesn't mean you're welcome.",
    advisories: [
      { category: "frightening", severity: 3, t: m(30),  note: "Hypnosis sequence — the paralysing 'Sunken Place'; deep dread." },
      { category: "profanity",   severity: 2, t: m(20),  note: "Strong language." },
      { category: "other",       severity: 2, t: m(60),  note: "Disturbing themes of racism and loss of bodily autonomy." },
      { category: "violence",    severity: 3, t: m(92),  note: "A bloody escape — impalement, a struggle, several deaths." },
    ],
  },
  {
    id: "la-la-land-2016",
    title: "La La Land",
    year: 2016,
    type: "movie",
    cert: "PG-13",
    runtime: m(128),
    genres: ["Romance", "Musical", "Drama", "Music"],
    tagline: "Here's to the fools who dream.",
    advisories: [
      { category: "profanity",   severity: 1, t: m(33),  note: "A handful of mild words." },
      { category: "substances",  severity: 1, t: m(45),  note: "Social drinking at parties." },
    ],
  },
  {
    id: "stranger-things",
    title: "Stranger Things",
    year: 2016,
    type: "tv",
    cert: "TV-14",
    runtime: m(51),
    genres: ["Sci-Fi", "Horror", "Drama"],
    tagline: "The world is turning upside down.",
    advisories: [
      { category: "profanity",   severity: 2, t: m(8),   note: "Teen language, occasionally strong." },
      { category: "frightening", severity: 3, t: m(15),  note: "The Demogorgon and the Upside Down — sustained creature horror." },
      { category: "violence",    severity: 2, t: m(38),  note: "Monster attacks; some blood and peril for the kids." },
    ],
  },
  {
    id: "game-of-thrones",
    title: "Game of Thrones",
    year: 2011,
    type: "tv",
    cert: "TV-MA",
    runtime: m(57),
    genres: ["Fantasy", "Drama", "Adventure"],
    tagline: "Winter is coming.",
    advisories: [
      { category: "nudity",      severity: 3, t: m(11),  note: "Frequent explicit nudity and sexual content across episodes." },
      { category: "violence",    severity: 3, t: m(24),  note: "Beheadings and battlefield gore." },
      { category: "profanity",   severity: 2, t: m(31),  note: "Strong language." },
      { category: "frightening", severity: 2, t: m(48),  note: "White Walkers and scenes of torture." },
    ],
  },
  {
    id: "breaking-bad",
    title: "Breaking Bad",
    year: 2008,
    type: "tv",
    cert: "TV-MA",
    runtime: m(47),
    genres: ["Crime", "Drama", "Thriller"],
    tagline: "Chemistry is the study of change.",
    advisories: [
      { category: "substances",  severity: 3, t: m(6),   note: "Methamphetamine production and use are central to the series." },
      { category: "violence",    severity: 3, t: m(22),  note: "Shootings and a graphic acid-disposal scene." },
      { category: "nudity",      severity: 1, t: m(30),  note: "Brief sexual content; partial nudity." },
      { category: "profanity",   severity: 2, t: m(15),  note: "Strong language." },
    ],
  },
  {
    id: "the-mandalorian",
    title: "The Mandalorian",
    year: 2019,
    type: "tv",
    cert: "TV-14",
    runtime: m(40),
    genres: ["Sci-Fi", "Action", "Adventure"],
    tagline: "This is the way.",
    advisories: [
      { category: "violence",    severity: 2, t: m(9),   note: "Blaster fights and bounty-hunting violence." },
      { category: "frightening", severity: 2, t: m(26),  note: "Creatures and moments of peril." },
    ],
  },
  {
    id: "avatar-last-airbender",
    title: "Avatar: The Last Airbender",
    year: 2005,
    type: "tv",
    cert: "TV-Y7",
    runtime: m(23),
    genres: ["Animation", "Adventure", "Fantasy", "Family"],
    tagline: "Water. Earth. Fire. Air.",
    advisories: [
      { category: "violence",    severity: 1, t: m(7),   note: "Martial-arts 'bending' battles; bloodless action." },
      { category: "frightening", severity: 1, t: m(16),  note: "A few intense moments for very young viewers." },
    ],
  },
  {
    id: "the-boys",
    title: "The Boys",
    year: 2019,
    type: "tv",
    cert: "TV-MA",
    runtime: m(60),
    genres: ["Action", "Comedy", "Crime"],
    tagline: "Never meet your heroes.",
    advisories: [
      { category: "violence",    severity: 3, t: m(5),   note: "Extreme gore — a person bursts in a spray of blood." },
      { category: "nudity",      severity: 3, t: m(18),  note: "Explicit nudity and sexual content throughout." },
      { category: "profanity",   severity: 3, t: m(22),  note: "Pervasive strong profanity." },
      { category: "substances",  severity: 2, t: m(40),  note: "Drug use ('Compound V' and recreational drugs)." },
    ],
  },
  {
    id: "lotr-fellowship-2001",
    title: "The Lord of the Rings: The Fellowship of the Ring",
    year: 2001,
    type: "movie",
    cert: "PG-13",
    runtime: m(178),
    genres: ["Fantasy", "Adventure", "Drama"],
    tagline: "One ring to rule them all.",
    advisories: [
      { category: "frightening", severity: 3, t: m(8),   note: "The Ringwraiths pursue the hobbits; relentless dread." },
      { category: "violence",    severity: 2, t: m(96),  note: "Battle with a cave troll and orcs in Moria." },
      { category: "frightening", severity: 3, t: m(120), note: "The Balrog on the bridge of Khazad-dûm; a character falls." },
    ],
  },
  {
    id: "coco-2017",
    title: "Coco",
    year: 2017,
    type: "movie",
    cert: "PG",
    runtime: m(105),
    genres: ["Animation", "Family", "Adventure", "Musical", "Music"],
    tagline: "The celebration of a lifetime.",
    advisories: [
      { category: "frightening", severity: 1, t: m(35),  note: "Friendly skeletons and the Land of the Dead; very mild scares." },
      { category: "other",       severity: 1, t: m(80),  note: "Emotional themes of death, memory and family loss." },
    ],
  },
  {
    id: "knives-out-2019",
    title: "Knives Out",
    year: 2019,
    type: "movie",
    cert: "PG-13",
    runtime: m(130),
    genres: ["Comedy", "Crime", "Mystery", "Thriller"],
    tagline: "Everyone's a suspect.",
    advisories: [
      { category: "profanity",   severity: 2, t: m(28),  note: "Some strong language." },
      { category: "violence",    severity: 2, t: m(46),  note: "Blood, a slit throat shown in flashback, themes of death." },
      { category: "substances",  severity: 1, t: m(70),  note: "Social drinking." },
    ],
  },
  {
    id: "whiplash-2014",
    title: "Whiplash",
    year: 2014,
    type: "movie",
    cert: "R",
    runtime: m(106),
    genres: ["Drama", "Music"],
    tagline: "The road to greatness can take you to the edge.",
    advisories: [
      { category: "profanity",   severity: 3, t: m(12),  note: "Relentless verbal abuse and strong profanity from the conductor." },
      { category: "violence",    severity: 1, t: m(80),  note: "A car crash; bloodied hands on the drum kit." },
    ],
  },
];

// expose for non-module script tags (works from file://)
window.MovieFilterr = { DATA, CATEGORIES, SEVERITY };
